[versions]
agp = "8.9.1"
circleimageview = "3.1.0"
colorpickerVersion = "1.1.0"
kotlin = "2.1.10"
coreKtx = "1.15.0"
coreSplashscreen = "1.0.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.2.1"
kotlinxCoroutinesAndroid = "1.9.0"
libsuVersion = "6.0.0"
navigationFragment = "2.8.9"
navigationFragmentKtx = "2.8.9"
navigationUiKtx = "2.8.9"
preferenceKtx = "1.2.1"
recyclerview = "1.4.0"
recyclerviewSelection = "1.1.0"
remotepreferences = "0.8"
xposedbridge = "main-SNAPSHOT"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationUiKtx" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-recyclerview-selection = { module = "androidx.recyclerview:recyclerview-selection", version.ref = "recyclerviewSelection" }
circleimageview = { module = "de.hdodenhof:circleimageview", version.ref = "circleimageview" }
jaredrummler-colorpicker = { module = "com.jaredrummler:colorpicker", version.ref = "colorpickerVersion" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
remotepreferences = { module = "com.crossbowffs.remotepreferences:remotepreferences", version.ref = "remotepreferences" }
su-core = { module = "com.github.topjohnwu.libsu:core", version.ref = "libsuVersion" }
su-nio = { module = "com.github.topjohnwu.libsu:nio", version.ref = "libsuVersion" }
su-service = { module = "com.github.topjohnwu.libsu:service", version.ref = "libsuVersion" }
xposedbridge = { module = "com.github.Mahmud0808:XposedBridge", version.ref = "xposedbridge" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

